;(function(){(on=function(){var a=this instanceof arguments.callee?"[on Constructor]":"[on Function]";return{toString:function(){return a}}}).toString=function(){return"[on]"};String.prototype[on]=function(a){return p(a,this.valueOf())};RegExp.prototype[on]=function(a){return p(a,this.source)};on.about=function(){on_about&&on_about(h)};var k,h=0,c={"not found":function(a,b){console.warn("[on] command: {"+b+"("+a+")} not found !")}};c["typeof"]=Object.prototype.toString;c.slice=function(a,b,f){0>a&&
(a+=this.length);0>b&&(b+=this.length);a=a||0;b=b||this.length;if(this.charAt)for(f=f||"";a<b;a+=1)f+=this.charAt(a);else for(f=f||[];a<b;a++)f.push(this[a]);return f};c.number={};c["pad left"]=c.number["pad left"]=function(a){return a?(0>this.valueOf()?"-":"")+("0000000000"+Math.abs(this.valueOf())).slice(-a):this.valueOf()};c.string={};c.event={};var n=window.addEventListener?["addEventListener",""]:["attachEvent","on"],m={},r=function(a){for(var b=q.length;--b;)if(a===q[b])return!0},q="load unload abort error scroll resize reset submit focus blur select change cut copy paste keydown keyup keypress touchstart touchend touchmove touchcancel contextmenu dblclick mousewheel DOMMouseScroll mousemove mouseover mouseout mousedown mouseup click".split(" ");
c["add event"]=c.event.add=function(a,b,f){a[n[0]](n[1]+f,function(f){k=h;h=10;b.call(a,f||window.event)},!1);h=k};c["bind event"]=c.event.bind=function(a,b){if(void 0==m[b])m[b]=[],document[n[0]](n[1]+b,function(a){k=h;h=11;a=a||window.event;for(var f=0,g=m[b].length;f<g;f++)m[b][f].call(a.srcElement||a.target,a);h=k},!1);else for(var f=m[b].length;f--;)if(a==m[b][f])return f;return m[b].push(a)};c.array={};c["for each item"]=c.array["for each"]=function(a){var b=0,f=this.length,d;for(d=f%8;d--;)if(!1===
a.call(this,b++))return!1;for(d=Math.floor(f/8);d--;)if(!1===a.call(this,b++)||!1===a.call(this,b++)||!1===a.call(this,b++)||!1===a.call(this,b++)||!1===a.call(this,b++)||!1===a.call(this,b++)||!1===a.call(this,b++)||!1===a.call(this,b++))return!1;return!0};c.hostlist={};c.object={};c["for each prop"]=c.object["for each"]=function(a){for(var b in this)if(this.hasOwnProperty(b)&&0==a.call(this,b))return!1;return!0};c["count props"]=c.object.count=function(a,b){var f=0,d;for(d in this)if(this.hasOwnProperty(d)&&
f++==a)return b?this[d]:d;return f};c.element={};c["for each child tN"]=c.element["for each child tN"]=function(a,b){for(var f=0,d=this.length;f<d;f+=1)if(1===this[f].nodeType&&this[f].tagName===b&&!1===a.call(this,f))return!1;return!0};c["new script"]=c.element["new script"]=function(a){var b=document.createElement("script");b.setAttribute("src",a);b.setAttribute("type","text/javscript");document.getElementsByTagName("head")[0].appendChild(b);return b};c["new css"]=c.element["new link"]=function(a){var b=
document.createElement("link");b.setAttribute("href",a);b.setAttribute("type","text/css");b.setAttribute("rel","stylesheet");document.getElementsByTagName("head")[0].appendChild(b);return b};c["new iframe"]=c.element["new iframe"]=function(a,b,f,d){var e;try{e=document.createElement('<iframe name="'+b+'" />')}catch(g){(e=document.createElement("iframe")).name=b}e.setAttribute("src",a);e.style.width=f;e.style.height=d;e.setAttribute("frameborder",0);this.appendChild(e);return e};c["new element"]=c.element["new"]=
function(a,b,f,d){a=document.createElement(a);a.setAttribute("class",b);a.setAttribute("id",f);d&&a.setAttribute("src",d);this.appendChild(a);return a};c.ajax=on.ajax={};c["ajax schedule"]=c.ajax.schedule=function(a,b,f,d){var e=c.ajax;1===e.busy.push(function(g){g.abort();for(var c in g.upload)g.upload[c]=a.upload[c];a.upload=null;for(c in a)g[c]=a[c];a=null;e[b](g,f,d)})&&function(){for(var b=e.quee[0]+1;--b||!setTimeout(arguments.callee,0);)if(!(e.quee[b]=e.quee[b]||e.xhro()).onreadystatechange){e.busy.shift()(e.quee[b]);
e.busy.length&&arguments.callee();break}}()};c["ajax request"]=c.ajax.request=function(a,b){var f={upload:{}};switch(b){default:f.onreadystatechange=function(){4===this.readyState&&(k=h,h=20,a.call(this,200!==this.status&&this.status),h=k,this.onreadystatechange=null)};break;case "load module":f.onreadystatechange=function(){if(4===this.readyState){if(200===this.status){k=h;var b=this.responseText;a.length?(h=23,new function(){try{eval(b)}catch(f){}finally{eval("("+a.toString()+").call(this,true)")}}):
(h=22,a.call(new function(){try{eval(b)}catch(a){}}));h=k}this.onreadystatechange=null}};break;case "load script":f.onreadystatechange=function(){if(4===this.readyState){if(200===this.status){k=h;h=21;try{eval(this.responseText)}finally{a()}h=k}this.onreadystatechange=null}}}return f};c["ajax xhro"]=c.ajax.xhro=function(){return new XMLHttpRequest||new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP")||null};c["ajax busy"]=c.ajax.busy=[];c["ajax quee"]=c.ajax.quee=[100];c["ajax POST"]=
c.ajax.POST=function(a,b,f){var d=b.indexOf("?")+1;a.GET=d?b.substr(d):null;a.POST=f||null;a.open("POST",b,!0);"string"===typeof f&&a.setRequestHeader("Content-type","application/x-www-form-urlencoded");a.send(a.POST)};c["ajax GET"]=c.ajax.GET=function(a,b,f){var d=b.indexOf("?")+1;a.POST=null;a.GET=f?(b+=(d?"&"+(f=b.substr(d)+"&"+f,""):"?")+f,f):d?b.substr(d):null;a.open("GET",b,!0);a.send(null)};on.event=new function(a){a=this;a.stopPropagation=function(){this.stopPropagation?this.stopPropagation():
this.cancelBubble=!0};a.preventDefault=function(){this.preventDefault?this.preventDefault():this.returnValue=!1};a.wheelDelta=function(){return this.wheelDelta||-40*this.detail};a.detail=function(){return this.detail||this.wheelDelta/-40}};on.iframe=new function(a){a=this;a.window=function(){var b=this;return b.contentWindow||b.window||(b=b.contentDocument||b.document).defaultView||b.parentWindow||null};a.document=function(){var b=this;return(b=b.contentDocument||b.contentWindow||b).document||b}};
on.document=new function(a){a=this;a.eachElementBy={};a.getElementsBy={};a.getElementsByTagName=a.getElementsBy.tagName=function(b){return(void 0===this.nodeType?document:this).getElementsByTagName(b)};a.eachElementByTagName=a.eachElementBy.tagName=function(b,a){return c["for each item"].call((void 0===this.nodeType?document:this).getElementsByTagName(b),a)};a.getElementById=function(b){return(void 0===this.nodeType?document:this).getElementById(b)};a.getElementsByClassPrefix=function(b){return a.getElementsByClassName.call(this,
b,void 0,!0)};a.getElementsByClassSuffix=function(b){return a.getElementsByClassName.call(this,b,void 0,void 0,!0)};a.getElementsByClassContains=function(b){return a.getElementsByClassName.call(this,b,void 0,!0,!0)};a.eachElementByClassPrefix=function(b,f){return a.eachElementByClassName.call(this,b,f,!0)};a.eachElementByClassSuffix=function(b,f){return a.eachElementByClassName.call(this,b,f,void 0,!0)};a.eachElementByClassContains=function(b,f){return a.eachElementByClassName.call(this,b,f,!0,!0)};
a.getElementsByClassName=a.getElementsBy.className=a.eachElementByClassName=a.eachElementBy.className=function(b,a,d,e){var g=void 0===this.nodeType?document:this;if(void 0===(d||e)&&document.getElementsByClassName){g=g.getElementsByClassName(b);if(void 0===a)return g;d=0;for(e=g.length;d<e;d+=1)if(0==a.call(g,d))return!1;return!0}var c=[],g=g.getElementsByTagName("*");b=(e?"":" ")+b+(d?"":" ");if(void 0===a){d=0;for(e=g.length;d<e;d+=1)0<=(" "+g[d].className+" ").indexOf(b)&&c.push(g[d]);return c}d=
0;for(e=g.length;d<e;d+=1)if(0<=(" "+g[d].className+" ").indexOf(b)&&0==a.call(g,d))return!1;return!0};a.getElementsByAttribute=a.getElementsBy.attribute=function(b,a){var d=void 0===this.nodeType?document:this;if(document.querySelectorAll)return d.querySelectorAll("["+b+(a?'="'+a+'"':"")+"]");var d=d.getElementsByTagName("*"),e=[];if(void 0!==a)for(var g=0,c=d.length,h;g<c;g+=1)(h=d[g].getAttribute(b))&&h==a&&e.push(d[g]);else for(g=0,c=d.length;g<c;g+=1)d[g].getAttribute(b)&&e.push(d[g]);return e};
a.eachElementByAttribute=a.eachElementBy.attribute=function(b,a,d){var e=void 0===this.nodeType?document:this;if(document.querySelectorAll)for(var e=e.querySelectorAll("["+b+(void 0!==a?'="'+a+'"':"")+"]"),c=0,h=e.length;c<h;c+=1){if(0==d.call(e,c))return!1}else if(e=e.getElementsByTagName("*"),void 0!==a)for(var c=0,h=e.length,l;c<h;c+=1){if((l=e[c].getAttribute(b))&&l==a&&0==d.call(e,c))return!1}else for(c=0,h=e.length;c<h;c+=1)if(e[c].getAttribute(b)&&0==d.call(e,c))return!1;return!0}};on.element=
new function(a){a=this;a.addClass=function(b){return-1==(" "+this.className+" ").indexOf(" "+b+" ")?this.className+=" "+b:!1};a.hasClass=function(b){return 0<=(" "+this.className+" ").indexOf(" "+(b||"")+" ")&&b};a.delClass=function(b){var a;return 0<=(a=(" "+this.className+" ").indexOf(" "+b+" "))?this.className=this.className.substr(0,a)+this.className.substr(a+b.length+1):!1};a.togClass=function(b){return a.hasClass.call(this,b)?a.delClass.call(this,b):a.addClass.call(this,b)};a.hasClasses=function(b){b=
b.split(" ");for(var a in b)if(-1==(" "+this.className+" ").indexOf(" "+b[a]+" "))return!1;return b.join(" ")};a.addClasses=function(b){b=b.split(" ");for(var f in b)a.addClass.call(this,b[f]);return b.join(" ")};a.delClasses=function(b){b=b.split(" ");for(var f in b)a.delClass.call(this,b[f]);return b.join(" ")};a.hasTagMatch=function(b){var a,d,e=/<([a-z]+)([^>]+)*>/;if(null!==(a=e.exec(b))&&this.tagName!==a[1].toUpperCase())return!1;for(e=RegExp("([a-zA-Z0-9-_]+)='([a-zA-Z0-9-_ ]+)'","g");null!==
(a=e.exec(b));)if("id"===a[1]){if(this.id!==a[2])return!1}else if("class"===a[1])for(d=(a[2]=a[2].split(" ")).length;d--;){if(-1===(" "+this.className+" ").indexOf(" "+a[2][d]+" "))return!1}else if(this.getAttribute(a[1])!==a[2])return!1;return!0};a.offset=function(b){for(var a=0,d=this;d;d=d.offsetParent)a+=d["offset"+b];return a};a.offsetTop=function(){return a.offset.call(this,"Top")};a.offsetLeft=function(){return a.offset.call(this,"Left")};a.nextElementSibling=function(){if(this.nextElementSibling)return this.nextElementSibling;
for(var b;(b=(b||this).nextSibling)&&1!==b.nodeType;);return b};a.innerText=function(){return this.innerText||this.textContent};a.toSubmitFormData=function(){var b="",a=encodeURIComponent,d;for(d in this)if("string"===typeof this[d])b+="&"+a(d)+"="+a(this[d]);else for(var e in this[d])b+="&"+a(d)+"["+e+"]="+a(this[d][e]);return b};a.getSubmitFormDataObject=function(){for(var a={},c=this,d=0,e,g;(c=c.parentNode)&&"FORM"!==c.tagName;);for(c=c.getElementsByTagName("*");e=c[d++];)switch((e.type||"").toLowerCase()){case "radio":case "checkbox":e.checked&&
(a[e.name||e.id]=e.value);break;case "select-multiple":for(var h=0;g=e.options[h++];)g.selected&&(a[e.name||e.id]=a[e.name||e.id]||[]).push(g.value||g.text);break;default:switch(e.tagName){case "INPUT":case "TEXTAREA":a[e.name||e.id]=e.value;break;case "SELECT":a[e.name||e.id]=(g=e.options[e.selectedIndex]).value||g.text}}return a};a.getSubmitFormData=function(a){for(var c="",d=this,e=0,g,h,l=encodeURIComponent;d&&"FORM"!==d.tagName;)d=d.parentNode;for(d=d.getElementsByTagName("*");g=d[e++];)switch((g.type||
"").toLowerCase()){case "file":if(a)return!1;case "radio":case "checkbox":g.checked&&(c+="&"+l(g.name||g.id)+"="+l(g.value));break;case "select-multiple":for(var k=0;h=g.options[k++];)h.selected&&(c+="&"+l(g.name||g.id)+"="+l(h.value||h.text));break;default:switch(g.tagName){case "INPUT":case "TEXTAREA":c+="&"+l(g.name||g.id)+"="+l(g.value);break;case "SELECT":c+="&"+l(g.name||g.id)+"="+l((h=g.options[g.selectedIndex]).value||h.text)}}return c}};on.submit=new function(a){a=this;a.toFormData=function(a){return on.element.toSubmitFormData.call(a)};
a.getFormDataObject=function(a){return on.element.getSubmitFormDataObject.call(a)};a.getFormData=function(a){return on.element.getSubmitFormData.call(a)}};on.form=new function(a){a=this;a.append=function(a,c){};a.upload={start:function(a){(this.upload=this.upload||{}).onloadstart=a},end:function(a){(this.upload=this.upload||{}).onloadend=a},complete:function(a){(this.upload=this.upload||{}).onload=a},error:function(a){(this.upload=this.upload||{}).onerror=a},abort:function(a){(this.upload=this.upload||
{}).onabort=a},progress:function(a){(this.upload=this.upload||{}).onprogress=a},request:function(a){for(var c in this.upload)a.upload[c]=this.upload[c],this.upload[c]=null;this.upload=null;return a}};a.data=function(a){try{return new FormData(a)}catch(c){return on.element.getSubmitFormData.call(a,!0)}};a.submit=function(b,f){for(var d=this,e;d&&"FORM"!==d.tagName;)d=d.parentNode;(e=a.data(d))?c.ajax.schedule(a.upload.request.call(d,c["ajax request"](b)),(f||d.method).toUpperCase(),d.action,e):(c["add event"](e=
c["new iframe"].call(d,"",+new Date,0,0),function(a){b.call({responseText:on.element.innerText.call(on.iframe.document.call(this).body)});d.removeAttribute("enctype");d.removeAttribute("encoding");d.removeAttribute("target");d.removeChild(this)},"load"),d.setAttribute("encoding","multipart/form-data"),d.setAttribute("enctype","multipart/form-data"),d.target=e.name,d.submit())}};var p=function(a,b,f){b=b||"";a=a||{};f=f||function(b){return"string"===typeof a?(b=document.getElementById(a))?(a=b,"element"):
"string":a.type&&(a.srcElement||a.target)?"event":void 0!=a.nodeType?"element":void 0!=a[0]&&void 0!=a[0].nodeType?"hostlist":"[object Array]"===c["typeof"].call(a)?"array":a/1===a?"number":"object"}();var d;if(d=c[f][b]||c[b])return function(){return d.apply(a,arguments)};switch(f){case "hostlist":if(r(b))return function(d){for(var f=a.length;f--;)c["add event"](a[f],d,b)};break;case "element":if(r(b))return document===a?function(a){return c["bind event"](a,b)}:function(d){return c["add event"](a,
d,b)};switch(b){case "for each":case "for each node":return function(b){return c.array["for each"].call(a.getElementsByTagName("*"),b)};case "for each child":return function(b){return c.array["for each"].call((a.body||a).children,b)};case "GET":case "POST":return function(c){return on.form.submit.call(a,c,b)};case "upload":return function(b){return on.form.upload.progress.call(a,b)}}if(0==b.indexOf("new "))return b=b.substr(4).toLowerCase(),function(d,f,h){return c["new element"].call(a.body||a,b,
d,f,h)};if(0==b.indexOf("for each child "))return b=b.substr(15).toUpperCase(),function(d){return c["for each child tN"].call((a.body||a).children,d,b)};if(0==b.indexOf("for each "))return b=b.substr(9).toUpperCase(),function(d){return c.array["for each"].call(a.getElementsByTagName(b),d)};if(0==b.indexOf("upload "))return b=b.substr(7).toLowerCase(),function(c){return on.form.upload[b].call(a,c)};break;case "string":switch(b){case "GET":case "POST":return function(d){c["ajax schedule"](c["ajax request"](d),
b,a)};case "load script":case "load module":return function(d){c["ajax schedule"](c["ajax request"](d,b),"GET",a)}}if(0==b.indexOf("POST "))return b=b.substr(5),function(d){c["ajax schedule"](c["ajax request"](d),"POST",a,b)};if(0==b.indexOf("GET "))return b=b.substr(4),function(d){c["ajax schedule"](c["ajax request"](d),"GET",a,b)}}return function(){return c["not found"](arguments,b)}}})

	("Behold, as the clay is in the potter's hand, so are ye in mine hand"/* Jeremiah 18:6 */);